### PR TITLE
Handle PartialStruct

### PR DESCRIPTION
**Pull request by YingboMa**
I am not sure how to create a test for this.

### CODE REVIEW

**Comment by timholy** [comment]
Very nice. For a test, can you design a function that produces a `PartialStruct` and then check for it using `find_callsites_by_ftt`?

**Comment by YingboMa** [comment]
I don't know how to write a small function that produces a `PartialStruct `. I discovered this when I was working on a pretty large codebase. Do you mind to write an example? I'd be happy to include it in this PR.

**Review by vchuravy — APPROVED** [review]

**Comment by timholy** [comment]
I think the best bet would be to hold off on merging this and locally have it throw `error("I got a PartialStruct, WHOOPPEEE!")` when it gets to PartialStruct. That way we'll notice when it happens and then we can add a test. Surely there's something small out there that generates one, and we'll just come across it in the ordinary course of business.

**Comment by YingboMa** [comment]
Since this fixes my use case, do you mind to merge it for now and make a release?

**Comment by timholy** [comment]
OK, just be sure to submit a test case if you stumble across something workable as a test.

**Comment by timholy** [comment]
I'd love to include #109, but I will leave it open for a bit longer and see if anyone wants to review it.

**Comment by timholy** [comment]
https://github.com/JuliaRegistries/General/pull/26833

**Pull request merged**
