### PR TITLE
WIP: Effects

### PR DESCRIPTION
**Pull request by Keno**
This is my WIP for adding effects printing to Cthulhu. @ianatol or @oscardssmith, could one of you rebase this (still needs #261 also), and a hotkey for toggling these on and off. Bonus points for also annotating effects in the source view, since I think that'd be most useful.

### CODE REVIEW

**Comment by ianatol** [comment]
Got reasonably far with this, including rebasing with #268, but gonna work on some other stuff for the rest of today and finish up tomorrow

**Comment by aviatesk** [comment]
I'm happy to have a review on it. Please ping me once it's ready.

**Comment by ianatol** [comment]
I'll ~~probably~~ have some questions for you before then, so you'll get to review even earlier ;)

**Comment by oscardssmith** [comment]
Close this now that https://github.com/JuliaDebug/Cthulhu.jl/pull/271 is merged?

**Pull request closed without merging**
