### PR TITLE
minor follow up on the tagged code instance change

### PR DESCRIPTION
**Pull request by aviatesk**
Requires JuliaLang/julia#53300.

### CODE REVIEW

**Comment by aviatesk** [comment]
There appears to be remaining issues related to world ages of `CthulhuInterpreter`. In the past, code instances were simply inserted into a dictionary maintained by `CthulhuInterpreter` and the cache existence was simply equivalent to the key existence. However, as they are now maintained as what could be considered "proper" `CodeInstance`s, we're encountering complex problems in test cases that include `do` blocks."

**Comment by Keno** [comment]
Do we actually want this, semantically? The fact that Cthulhu's cache is not poisoned by prior results is one of the best features about it. Also, I don't really see any benefit here. You're not likely to want to cache Cthulhu results in precompile files, etc.

**Comment by vchuravy** [comment]
>Do we actually want this, semantically? 

Yeah I was thinking about this as well and that's why in #540 I kept using the old design. Each instance of the abstract interpreter currently get's a fresh cache.

**Comment by aviatesk** [comment]
Yeah, I agree that the current design with the external code cache is a good fit for Cthulhu.

**Pull request merged**
