### PR TITLE
adapt to julia nightly changes

### LINKED ISSUE #575: `_dump_function_llvm` errors when printing LLVM IR on nightly
https://github.com/JuliaLang/julia/commit/db25494f62b78372c745053dc2a0644847bfab33 changed the signature of `_dump_function_llvm` such that the second argument is no longer `world::UInt` but now `src::Core.CodeInfo`.

```julia
ERROR: MethodError: no method matching _dump_function_llvm(::Core.MethodInstance, ::UInt64, ::Bool, ::Bool, ::Bool, ::Bool, ::Symbol, ::Base.CodegenParams)
The function `_dump_function_llvm` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  _dump_function_llvm(::Core.MethodInstance, ::Core.CodeInfo, ::Bool, ::Bool, ::Bool, ::Bool, ::Symbol, 
::Base.CodegenParams)
   @ InteractiveUtils C:\Users\gag\Documents\Code\julia\usr\share\julia\stdlib\v1.12\InteractiveUtils\src\codeview.jl:285

Stacktrace:
  [1] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\codeview.jl:25
  [2] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\codeview.jl:25
  [3] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:740
  [4] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:397
  [5] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:791
  [6] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:791
  [7] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:807
  [8] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:804
  [9] __descend_with_error_handling(args::Any; terminal::Any, kwargs...)
    @ Cthulhu C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:222
 [10] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:219
 [11] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:211
 [12] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:203
 [13] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:169
 [14] top-level scope
    @ C:\Users\gag\.julia\packages\Cthulhu\8y2RA\src\Cthulhu.jl:169
 [15] top-level scope
    @ REPL[31]:1
```

### LINKED ISSUE #586: `do_typeinf!(interp, mi)` does not always put `mi` into cache
On nightly, the following returns false:

```julia-repl
julia> using Cthulhu

julia> mi = Core.Compiler.specialize_method(Base._methods(seekstart, (IOBuffer,), -1, Base.get_world_counter())[])
MethodInstance for seekstart(::IOBuffer)

julia> interp = Cthulhu.CthulhuInterpreter()
Cthulhu.CthulhuInterpreter(Core.Compiler.NativeInterpreter(...), IdDict{Union{Core.Compiler.InferenceResult, Core.MethodInstance}, Cthulhu.InferredSource}(), IdDict{Core.MethodInstance, Core.CodeInstance}(), IdDict{Union{Core.Compiler.InferenceResult, Core.MethodInstance}, Vector{Pair{Int64, String}}}(), IdDict{Union{Core.Compiler.InferenceResult, Core.MethodInstance}, Dict{Int64, Core.Compiler.Effects}}(), IdDict{Union{Core.Compiler.InferenceResult, Core.MethodInstance}, Dict{Int64, Any}}())

julia> Cthulhu.do_typeinf!(interp, mi)

julia> mi in keys(interp.opt)
false
```

whereas on 1.11:

```julia-repl
julia> mi in keys(interp.opt)
true
```

This causes e.g. `@descend annotate_source=false seekstart(IOBuffer())` to error. Perhaps this is a regression in base?

### PR DESCRIPTION
**Pull request by simeonschaub**
I'm not sure whether this is the correct way to do it, but this fixes #586 locally for me.

Also fixes #575

### CODE REVIEW

**Review by aviatesk — APPROVED** [review]
Thanks so much. This looks great.

**Comment by simeonschaub** [comment]
Thanks for the review! The only thing I'm a little worried about is `cthulhu_llvm` and `cthulhu_native` now having different signatures on different Julia versions. Is that an issue? They're not really meant to be used directly, right?

**Comment by aviatesk** [comment]
I don't think they're supposed to be used interchangeably👍 @vchuravy you may possibly have a different opinion?

**Comment by aviatesk** [comment]
SGTM.

**Pull request merged**
