### PR TITLE
adjustments to JuliaLang/julia#52415

### PR DESCRIPTION
**Pull request by aviatesk**
/cc @vtjnash

### CODE REVIEW

**Comment by aviatesk** [comment]
This PR leverages the new type printing feature from #52415:
image

**Comment by vtjnash** [comment]
Seems to be a less complete version of https://github.com/JuliaDebug/Cthulhu.jl/pull/526? That was currently blocked on getting my PRs for JuliaInterpreter merged so it works on Julia v1.11+ again

I am excited to see the new type printing feature getting used, but I am skeptical that other folks will want to have doubled (or more) the number of contextual lines that get printed by default. It might need to be opt-in in some way?

**Comment by aviatesk** [comment]
Oops, I didn't notice you'd already put in a PR. My bad. Anyway, why should we prioritize merging JuliaInterpreter? Since Cthulhu doesn't rely on JuliaInterpreter, we could update it on its own, right? It sounds like updating JuliaInterpreter might take a bit while.

**Comment by aviatesk** [comment]
Regarding the extra debug information, I believe it should be okay because `:source`-mode is already an opt-in feature.

**Comment by vtjnash** [comment]
I thought this relied on it. But maybe that was Revise instead that relies on it?

**Pull request closed without merging**
