### PR TITLE
restore original intent of IRShow test case

### PR DESCRIPTION
**Pull request by simeonschaub**
I think this makes this a better test case, since the small union did
not show up here before.

### CODE REVIEW

**Comment by aviatesk** [comment]
We actually need to further update test outputs

**Comment by vchuravy** [comment]
@simeonschaub  bump? Probably needs a rebase as well.

**Comment by simeonschaub** [comment]
The issue here is that my previous approach that replaced `code_coverage_effect` statements with `nothing` and then runs dce on the IR deletes other code here as well, leading to different results when code-coverage is enabled. Is there a better way to delete statements from `IRCode`?

**Comment by simeonschaub** [comment]
Ok, this now uses PerformanceTestTools.jl for the tests instead of manually messing with the IR, which should be a lot more reliable than the current approach. I also moved the organization of the tests around a bit for this, I hope that's ok.

**Comment by simeonschaub** [comment]
> We actually need to further update test outputs ?

Just to clarify, I just made a typo previously, so the tests weren't testing the printing for small unions as I thought. We hopefully don't have to touch these tests after this for a while.

**Pull request merged**
